#include<stdio.h>



// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.


int __LIMIT__ = 4000000;

int main (void)
{
  int sum = 0;
  int prev = 1;

  for (int i = 2; i <= __LIMIT__; ) {
    if (i % 2 == 0) {
      sum += i;
    }

    i = i + prev;
    prev = i - prev;
  }
  printf("sum: %i\n", sum);
  return 0;
}
